builds:
  -
    binary: ld-find-code-refs
    main: ./cmd/ld-find-code-refs/
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64

nfpm:
  name_template: "{{ .ProjectName }}_{{ .Version }}.{{ .Arch }}"

  homepage: https://launchdarkly.com/
  maintainer: LaunchDarkly <team@launchdarkly.com>
  description: Job for finding and sending feature flag code references to LaunchDarkly
  license: Apache 2.0
  vendor: LaunchDarkly

  formats:
  - deb
  - rpm

  replacements:
    386: i386

release:
  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  prerelease: auto

brew:
  name: ld-find-code-refs

  description: Job for finding and sending feature flag code references to LaunchDarkly

  homepage: "https://launchdarkly.com"

  github:
    owner: launchdarkly
    name: homebrew-tap

  folder: Formula

  url_template: "https://github.com/launchdarkly/ld-find-code-refs/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

  install: |
    bin.install "ld-find-code-refs"

  commit_author:
    name: LaunchDarklyCI
    email: dev@launchdarkly.com

