before:
  hooks:
  - make compile-github-actions-binary

builds:
  -
    binary: git-flag-parser
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - 386
      - amd64

release:
  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  prerelease: auto

dockers:
  - image_templates:
    -  ldactions/git-flag-parser-gh-action:latest
    -  ldactions/git-flag-parser-gh-action:{{ .Tag }}
    goos: linux
    goarch: amd64
    dockerfile: parse/github-actions/Dockerfile
    extra_files:
    - parse/github-actions/github-actions-flag-parser
